@Library('sampleLibrary')_
pipeline{
    agent any
    stages{
        stage('Download'){
            steps{
                script{
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('Build'){
            steps{
                script{
                    cicd.buildArtifact()
                }
            }
        }
        stage('Deploy'){
            steps{
                script{
                    cicd.deployTomcat("Declarative_Pipeline_Sharedlibrary","172.31.22.245","testapp")
                }
            }
        }
        stage('Testing'){
            steps{
                script{
                    cicd.gitDownload("FunctionalTesting")
                    cicd.testSelenium("Declarative_Pipeline_Sharedlibrary")
                }
            }
        }
    }
}
